<!DOCTYPE HTML>
<html lang="en">
<head>
    <style>
        h1,h2,h3{
           text-align: center;
        }
    </style>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>404 Error</title>
</head>
<body>
<h1>ERROR 404:PAGE NOT FOUND</h1>
<h2>Sorry the page you were looking for has not been found</h2>
<h3>Look at your URL you probably have a mistake somewhere</h3>

</body>
</html>