
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Inchoo PHP Academy 2019</title>
</head>
<form action="<?php echo App::config('url')?>/Index/deletePost/<?= $post->getId() ?>" method="post" enctype="multipart/form-data">
<div class="container">
    <center><h1>Post</h1></center>

<h1>Content of your post: <?= htmlspecialchars($post->getContent()) ?></h1>
    <h3>Comments:</h3><?php foreach ($comments as $comment): ?>
        <p>
                <?= htmlspecialchars($comment->getContent()) ?>
        </p>
    <?php endforeach; ?>

<input type="submit" class="btn btn-danger" name="delete" value="Delete">

</div>
</form>

<form method="post" action="<?php echo App::config('url')?>/Index/newComment/<?= $post->getId() ?>">

    <div class="form-group">
        <lable for="content">Enter your comment:</lable>
        <input id="content" name="content">
    </div>
    <input type="submit" class="btn btn-primary" value="Submit comment">

    <form action="<?php echo App::config('url')?>">
        <input type="submit" value="Home Page">
    </form>
</form>

<form method="post" action="<?php echo App::config('url')?>/Index/imageUpload/<?= $post->getId() ?>" enctype="multipart/form-data">
    <div>
        <h3>Upload image:</h3>
        <input type="file" name="fileToUpload">
        <input type="submit" name="submit" value="Upload">
    </div>

</form>
</body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>