
<div class="container">
    <center><h1>Post</h1></center>

<h1>Content of your post: <?= htmlspecialchars($post->getContent()) ?></h1>
    <h3>Comments:</h3><?php foreach ($comments as $comment): ?>
        <p>
                <?= htmlspecialchars($comment->getContent()) ?>
        </p>
    <?php endforeach; ?>

<input type="submit" class="btn btn-danger" name="delete" value="Delete">

</div>
</form>

<form method="post" action="<?php echo App::config('url')?>Index/newComment/<?= $post->getId() ?>">

    <div class="form-group">
        <lable for="content">Enter your comment:</lable>
        <input id="content" name="content">
    </div>
    <input type="submit" class="btn btn-primary" value="Submit comment">

    <form action="<?php echo App::config('url')?>">
        <input type="submit" value="Home Page">
    </form>
</form>

<form method="post" action="<?php echo App::config('url')?>Index/imageUpload/<?= $post->getId() ?>" enctype="multipart/form-data">
    <div>
        <h3>Upload image:</h3>
        <input type="file" name="fileToUpload">
        <input type="submit" name="submit" value="Upload">
    </div>

</form>
